import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import os
import time

# Set page config
st.set_page_config(
    page_title="Circadian Rhythm Anomaly Detector",
    layout="wide",
    page_icon="🧬",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap');
    html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
    .main { background-color: #0E1117; }
    .metric-card {
        background: linear-gradient(135deg, #1E2329 0%, #252D3A 100%);
        border-radius: 12px;
        padding: 20px;
        border: 1px solid #2D3748;
    }
    .doctor-tip {
        background: linear-gradient(135deg, #0d2137 0%, #0a3251 100%);
        border-left: 4px solid #00CC96;
        border-radius: 8px;
        padding: 16px;
    }
    h1 { color: #E0E6ED !important; }
    h2, h3 { color: #A0AEC0 !important; }
    </style>
""", unsafe_allow_html=True)

# ─── HEADER ───────────────────────────────────────────────────────────────────
st.title("🧬 Circadian Rhythm Anomaly Detection")
st.markdown("**Real-time Monitoring & Deep Learning Analytics Dashboard**")
st.markdown("A lightweight autoencoder trained on wearable sensor data to detect circadian rhythm disruptions.")
st.markdown("---")

# ─── SIDEBAR ──────────────────────────────────────────────────────────────────
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/2491/2491528.png", width=80)
    st.markdown("## ⚙️ Settings")
    st.markdown("---")
    uploaded_file = st.file_uploader(
        "📂 Upload `dashboard_data` (generated by `anomaly_detector.py`)",
        help="Upload the generated dataset file (up to 2GB supported). Any extension is supported as long as it contains the required columns."
    )
    st.markdown("---")
    st.markdown("### 📌 About")
    st.markdown("""
    - **Model**: Lightweight Autoencoder (PyTorch)  
    - **Threshold**: 95th Percentile Reconstruction Error  
    - **Data**: Apple Watch Heart Rate & Step Count  
    - **Window**: 24-hour circadian cycle  
    """)
    st.markdown("---")
    st.markdown("**SDGs:** 🌱 Goal 3 · ⚙️ Goal 9")

# ─── DATA LOADING ─────────────────────────────────────────────────────────────
@st.cache_data
def load_data_from_file(file):
    try:
        df = pd.read_csv(file)
        if 'timestamp' not in df.columns:
            st.error("❌ Invalid format: The uploaded file does not have the required 'timestamp' column. Please upload the data generated by the anomaly detector.")
            return None
        df['timestamp'] = pd.to_datetime(df['timestamp'])
        return df
    except Exception as e:
        st.error(f"❌ Error reading file: {e}. Please ensure you are uploading the correct `dashboard_data.csv` style format.")
        return None

@st.cache_data
def load_local_data():
    current_dir = os.path.dirname(os.path.abspath(__file__))
    data_path = os.path.join(current_dir, "dashboard_data.csv")
    if os.path.exists(data_path):
        df = pd.read_csv(data_path)
        df['timestamp'] = pd.to_datetime(df['timestamp'])
        return df
    return None

# Load data: uploaded > local file
if uploaded_file is not None:
    df = load_data_from_file(uploaded_file)
else:
    df = load_local_data()

# ─── MAIN DASHBOARD ───────────────────────────────────────────────────────────
if df is not None:
    df['is_anomaly'] = df['is_anomaly'].fillna(False).astype(bool)
    anomalies_df = df[df['is_anomaly']]
    normal_df = df[~df['is_anomaly']]
    threshold_val = df['threshold'].iloc[0]

    # ── Feature Analysis ──────────────────────────────────────────────────────
    hr_std_norm = normal_df['HeartRate'].std()
    hr_std_anom = anomalies_df['HeartRate'].std() if len(anomalies_df) > 0 else 0
    step_std_norm = normal_df['StepCount'].std()
    step_std_anom = anomalies_df['StepCount'].std() if len(anomalies_df) > 0 else 0

    hr_deviation = (hr_std_anom - hr_std_norm) / hr_std_norm if hr_std_norm > 0 else 0
    step_deviation = (step_std_anom - step_std_norm) / step_std_norm if step_std_norm > 0 else 0
    primary_cause = "Heart Rate" if hr_deviation > step_deviation else "Step Count"

    # ── Model Evaluation Metrics ───────────────────────────────────────────────
    total_params = (48 * 16) + 16 + (16 * 8) + 8 + (8 * 16) + 16 + (16 * 48) + 48  # Autoencoder params
    
    total_hours = len(df)
    total_anomalies = len(anomalies_df)
    anomaly_rate = (total_anomalies / total_hours) * 100 if total_hours > 0 else 0

    # ── KPI Metrics Row ───────────────────────────────────────────────────────
    st.subheader("📊 Key Performance Indicators")
    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("🕐 Monitored Hours", f"{total_hours:,}")
    c2.metric("⚠️ Anomalies Detected", f"{total_anomalies:,}")
    c3.metric("📈 Anomaly Rate", f"{anomaly_rate:.2f}%")
    c4.metric("🔑 Primary Driver", primary_cause)
    c5.metric("🤖 Model Parameters", f"{total_params:,}")

    st.markdown("---")

    # ── Model Evaluation Section ───────────────────────────────────────────────
    st.subheader("🔬 Model Evaluation & Efficiency Metrics")
    ev1, ev2, ev3, ev4 = st.columns(4)
    with ev1:
        st.metric("Architecture", "MLP Autoencoder")
        st.caption("Lightweight & resource-efficient")
    with ev2:
        st.metric("Latent Dimension", "8 neurons")
        st.caption("Compact representation of circadian cycle")
    with ev3:
        st.metric("Anomaly Threshold", f"{threshold_val:.4f}")
        st.caption("95th percentile of training reconstruction errors")
    with ev4:
        # Compute anomaly precision-like metric based on std deviation ratio
        separation = abs(hr_deviation if primary_cause == "Heart Rate" else step_deviation)
        quality = min(99.9, 50 + separation * 20)
        st.metric("Detection Confidence", f"{quality:.1f}%")
        st.caption("Based on anomaly vs. normal variance separation")

    # Attribution chart
    st.markdown("#### 📉 Feature Anomaly Attribution")
    attr_fig = go.Figure(go.Bar(
        x=['Heart Rate Deviation', 'Step Count Deviation'],
        y=[max(0, hr_deviation * 100), max(0, step_deviation * 100)],
        marker_color=['#EF553B' if primary_cause == 'Heart Rate' else '#636EFA',
                      '#636EFA' if primary_cause == 'Heart Rate' else '#EF553B'],
        text=[f"{max(0, hr_deviation*100):.1f}%", f"{max(0, step_deviation*100):.1f}%"],
        textposition='outside'
    ))
    attr_fig.update_layout(
        template="plotly_dark",
        yaxis_title="Deviation from Normal (%)",
        title="Which feature deviated most during anomalies",
        height=300
    )
    st.plotly_chart(attr_fig, use_container_width=True)

    st.markdown("---")

    # ── Doctor's Recommendations ───────────────────────────────────────────────
    st.subheader("👨‍⚕️ Digital Doctor's Analysis & Recommendations")

    if total_anomalies == 0:
        st.success("✅ **Doctor's Note:** Your circadian rhythm looks exceptional. Keep up the routine!")
    else:
        st.warning(
            f"⚠️ **Doctor's Note:** We detected **{total_anomalies} hours** of circadian disruption "
            f"({anomaly_rate:.1f}% of monitored time). The primary metric responsible is **{primary_cause}**."
        )
        
        col_doc1, col_doc2 = st.columns(2)
        
        with col_doc1:
            st.markdown("##### 🫀 Heart Rate Recommendations")
            if primary_cause == "Heart Rate":
                st.error("⬆️ **PRIMARY DRIVER** — Heart Rate anomalies are dominant")
            st.info("""
**1. Limit Stimulants Before Bed**  
Avoid caffeine, alcohol, or heavy meals at least 4–6 hours before sleep.

**2. Manage Stress Actively**  
Practice 10–15 min of meditation, box breathing, or progressive muscle relaxation before bed.

**3. Stay Hydrated**  
Mild dehydration can cause elevated resting heart rate. Aim for 8 glasses of water daily.

**4. Seek Medical Advice if Persistent**  
Consistently elevated resting HR (>100 bpm) warrants a doctor's consultation for cardiovascular screening.
            """)

        with col_doc2:
            st.markdown("##### 👟 Activity & Sleep Schedule Recommendations")
            if primary_cause == "Step Count":
                st.error("⬆️ **PRIMARY DRIVER** — Activity pattern anomalies are dominant")
            st.info("""
**1. Morning Sunlight Exposure**  
Get 10–15 min of natural sunlight within 30 min of waking. This anchors your biological clock.

**2. Consistent Sleep–Wake Times**  
Wake at the same time every day — even weekends. Irregular schedules are a leading cause of circadian misalignment.

**3. Avoid Evening Vigorous Exercise**  
Keep intense workouts (cardio/weights) to morning or late afternoon. Avoid 2–3 hrs before sleep.

**4. Break Up Sedentary Periods**  
Stand or walk for 5 min every hour during the day. Prolonged inactivity disrupts metabolic rhythms.
            """)

        # Time of day distribution for anomalies
        if len(anomalies_df) > 0:
            st.markdown("##### 🕐 When Do Anomalies Occur? (Hour of Day)")
            anomalies_df2 = anomalies_df.copy()
            anomalies_df2['hour'] = anomalies_df2['timestamp'].dt.hour
            hour_counts = anomalies_df2.groupby('hour').size().reset_index(name='count')
            fig_hour = px.bar(
                hour_counts, x='hour', y='count',
                color='count',
                color_continuous_scale='Reds',
                labels={'hour': 'Hour of Day (0=Midnight)', 'count': 'Anomaly Occurrences'},
                title="Distribution of Anomaly Hours"
            )
            fig_hour.update_layout(template="plotly_dark", height=300, showlegend=False)
            st.plotly_chart(fig_hour, use_container_width=True)

    st.markdown("---")

    # ── Heart Rate Timeline ────────────────────────────────────────────────────
    st.subheader("❤️ Heart Rate Timeline")
    st.caption("Green = Normal | Red ✕ = Anomaly detected")
    fig_hr = go.Figure()
    fig_hr.add_trace(go.Scatter(
        x=df['timestamp'], y=df['HeartRate'],
        mode='lines', name='Heart Rate',
        line=dict(color='#00CC96', width=1.5)
    ))
    fig_hr.add_trace(go.Scatter(
        x=anomalies_df['timestamp'], y=anomalies_df['HeartRate'],
        mode='markers', name='Anomaly',
        marker=dict(color='#EF553B', size=7, symbol='x')
    ))
    fig_hr.update_layout(template="plotly_dark", hovermode="x unified", height=380)
    st.plotly_chart(fig_hr, use_container_width=True)

    # ── Step Count Bar ─────────────────────────────────────────────────────────
    st.subheader("🚶 Step Count Activity")
    st.caption("Red bars = anomalous hours | Blue bars = normal hours")
    fig_steps = px.bar(
        df, x='timestamp', y='StepCount',
        color='is_anomaly',
        color_discrete_map={False: '#636EFA', True: '#EF553B'},
        labels={'is_anomaly': 'Anomaly'}
    )
    fig_steps.update_layout(template="plotly_dark", bargap=0, height=350)
    st.plotly_chart(fig_steps, use_container_width=True)

    # ── Reconstruction Error ───────────────────────────────────────────────────
    st.markdown("---")
    st.subheader("🤖 Autoencoder Reconstruction Error")
    st.caption("The model flags sequences where reconstruction error exceeds the learned threshold (red dashed line).")
    fig_err = go.Figure()
    fig_err.add_trace(go.Scatter(
        x=df['timestamp'], y=df['reconstruction_error'],
        mode='lines', name='Reconstruction Error',
        line=dict(color='#AB63FA', width=1.5)
    ))
    fig_err.add_hline(
        y=threshold_val, line_dash='dash', line_color='red',
        annotation_text=f"Threshold ({threshold_val:.4f})",
        annotation_position="top left"
    )
    fig_err.add_trace(go.Scatter(
        x=anomalies_df['timestamp'], y=anomalies_df['reconstruction_error'],
        mode='markers', name='Above Threshold',
        marker=dict(color='#EF553B', size=5)
    ))
    fig_err.update_layout(template="plotly_dark", hovermode="x unified", height=300)
    st.plotly_chart(fig_err, use_container_width=True)

    # ── Raw Data Table ─────────────────────────────────────────────────────────
    with st.expander("📋 View Raw Data Table"):
        st.dataframe(
            df[['timestamp', 'HeartRate', 'StepCount', 'reconstruction_error', 'is_anomaly']].sort_values('timestamp'),
            use_container_width=True
        )

else:
    st.info("👈 **Upload your `dashboard_data.csv` file** in the sidebar to load your personal analysis.")
    st.markdown("""
    ### How to generate your data:
    ```bash
    # Step 1: Parse Apple Health export
    python parse_health_data.py
    
    # Step 2: Train autoencoder & detect anomalies
    python anomaly_detector.py
    
    # Step 3: Upload the generated dashboard_data.csv in the sidebar
    ```
    """)
